name: Deploy ttasup-frontend to S3

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: family  # 모든 run 명령이 이 폴더(family)에서 실행됨

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build Next.js # next.config.js의 output: 'export' 설정에 따라 'out' 폴더가 'family/out' 경로에 생성됨
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Sync to S3
        # 'family/out'을 가리키는 부분
        run: aws s3 sync ./out s3://${{ secrets.S3_BUCKET_NAME }} --delete

      # CloudFront 사용
      - name: Invalidate CloudFront cache
        if: success()
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"